package com.example.blablaplane.object.user;

import com.example.blablaplane.object.aircraft.Aircraft;
import com.example.blablaplane.object.trip.Trip;
import com.google.firebase.database.PropertyName;

import java.util.ArrayList;
import java.util.List;

public class User {

    private List<Aircraft> aircraftList;
    private List<Trip> myTripList;
    /**
     * The unique id of the user generated by Firebase
     */
    private String id;
    private String name;
    private String surname;
    private String email;
    private String password;
    private String phone;
    private float rating;

    public User() {
        // Constructor for Firebase
    }

    public User(String name, String surname, String email, String password, String phone, float rating) {
        this(name, surname, email, password, phone, rating, new ArrayList<>());
    }

    public User(String name, String surname, String email, String password, String phone, float rating, ArrayList<Aircraft> aircraftList) {
        this(name, surname, email, password, phone, rating, aircraftList, new ArrayList<>());
    }

    public User(String name, String surname, String email, String password, String phone, float rating, ArrayList<Aircraft> aircraftList, ArrayList<Trip> myTripList) {
        this.id = email.replace("@", "").replace(".", "");
        this.name = name;
        this.surname = surname;
        this.email = email;
        this.password = password;
        this.phone = phone;
        this.rating = rating;
        this.aircraftList = aircraftList;
        this.myTripList = myTripList;
    }

    public List<Trip> getMyTripList() {
        return myTripList;
    }

    public boolean addNewTrip(Trip trip) {
        return this.myTripList.add(trip);
    }

    public String getId() {
        return this.id;
    }

    public String getName() {
        return this.name;
    }

    public String getSurname() {
        return this.surname;
    }

    public String getEmail() {
        return this.email;
    }

    public String getPassword() {
        return this.password;
    }

    public String getPhone() {
        return this.phone;
    }

    public String getRatingString() {
        return "★ " + this.rating + "/5";
    }

    public float getRating() {
        return this.rating;
    }

    public void addAircraft(Aircraft aircraft) {
        this.aircraftList.add(aircraft);
    }

    public void removeAircraft(Aircraft aircraft) {
        this.aircraftList.remove(aircraft);
    }

    public void setAircraftList(List<Aircraft> aircraftList) {
        this.aircraftList = aircraftList;
    }

    public List<Aircraft> getAircraftList() {
        return this.aircraftList;
    }

    public void setName(String name) {
        this.name = name;
    }

    public void setSurname(String surname) {
        this.surname = surname;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    public void setPhone(String phone) {
        this.phone = phone;
    }

    public void setRating(float rating) {
        this.rating = rating;
    }
}
