name: CI

on:
  workflow_dispatch:
  pull_request:
    branches: 
      - "develop"
      - "cicd"
  
  

jobs:

  integrationTests:
    runs-on: macos-latest
      
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with: 
          distribution: corretto
          java-version: 17
      - uses: gradle/gradle-build-action@v2

      - name: Setup emulators
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 33
          script: ./gradlew connectedCheck
        
      - name: Run integrationTests
        run: ./gradlew connectedAndroidTest 

  sonarqube:
    runs-on: ubuntu-latest
      
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with: 
          distribution: corretto
          java-version: 17
      - uses: gradle/gradle-build-action@v2
        
      - name: Run SonarQube
        run: ./gradlew sonar
