name: CI

on:
  push:
    branches:
      - 'develop'
  pull_request:
    branches: 
      - 'develop'
      
  workflow_dispatch:
  

jobs:
  build:
    runs-on: ubuntu-latest
      
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-iava@v3
      - uses: gradle/gradle-build-action@v2

      - name: build project
        run: ./gradlew build
        
      

  linter:
    runs-on: ubuntu-latest
      
    steps:
      - uses: actions/checkout@v3
        
      - name: Run Linter
        run: ./gradlew lintDebug
          
      - name: Upload html report
        uses: actions/upload-artifact@v2
        with:
          name: index.html
          path: app/build/reports/lints-results-debug.html
