name: CI

on:
  workflow_dispatch:
  push:
    branches:
      - "develop"
      - "cicd"
  pull_request:
    branches: 
      - "develop"
      - "cicd"
  
  

jobs:
  build:
    runs-on: ubuntu-latest
      
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with: 
          distribution: corretto
          java-version: 17
      - uses: gradle/gradle-build-action@v2

      - name: build project
        run: ./gradlew build
        
      

  linter:
    runs-on: ubuntu-latest
      
    steps:
      - uses: actions/checkout@v3
        
      - name: Run Linter
        run: ./gradlew lintDebug
          
      - name: Upload html report
        uses: actions/upload-artifact@v2
        with:
          name: index.html
          path: app/build/reports/lint-results-debug.html

  sonarqube:
    runs-on: ubuntu-latest
      
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with: 
          distribution: corretto
          java-version: 17
      - uses: gradle/gradle-build-action@v2
        
      - name: Run SonarQube
        run: ./gradlew sonar
