name: CI

on:
  workflow_dispatch:
  
  pull_request:
    branches: 
      - "develop"
      - "cicd"
  
  

jobs:
         
  linter:
    runs-on: ubuntu-latest
      
    steps:
      - uses: actions/checkout@v3
        
      - name: Run Linter
        run: ./gradlew lintDebug
          
      - name: Upload html report
        uses: actions/upload-artifact@v2
        with:
          name: index.html
          path: app/build/reports/lint-results-debug.html

  integrationTests:
    runs-on: ubuntu-latest
      
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with: 
          distribution: corretto
          java-version: 17
      - uses: gradle/gradle-build-action@v2
        
      - name: Run integration tests
        run: ./gradlew cAD

  sonarqube:
    runs-on: ubuntu-latest
      
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with: 
          distribution: corretto
          java-version: 17
      - uses: gradle/gradle-build-action@v2
        
      - name: Run SonarQube
        run: ./gradlew connectedAndroidTest 
