name: CI

on:
  push:
    branches:
      - 'develop'
  pull_request:
    branches: 
      - 'develop'
      
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
        type: choice
        options:
        - info
        - warning
        - debug
  
jobs:
  build:
    runs-on: ubuntu-latest
      
    steps:
      - uses: actions/checkout@v2
        
      - name: Run Linter
        run: ./gradlew lintDebug
          
      - name: Upload html report
        uses: actions/upload-artifact@v2
        with:
          name: index.html
          path: app/build/reports/lints-results-debug.html
